playlist/course_video/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path

from .views import *

app_name = "course_video"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("course", Main.as_view(), name="course"),
    path("add", AddCourse.as_view(), name="add"),
    path("listing/<int:id>/", Listing.as_view(), name="listing"),
    path("editing/<int:id>/", Editing.as_view(), name="editing"),
    path("tag_listing/<slug:tags>/", TagListing.as_view(), name="tag_listing"),
    path("search", Search.as_view(), name="search"),
    path("getstatus/<int:id>", GetStatus.as_view(), name="getstatus"),
    path("clone/<int:id>", Clone.as_view(), name="clone"),
    path("course_csv", CourseCsv.as_view(), name="course_csv"),
    path("upload", Upload.as_view(), name="upload"),
    path("download", Download.as_view(), name="download"),
]

playlist/members/urls.py
from django.urls import path

from members.views import *

app_name = "members"

urlpatterns = [
    path("signup", HandleSignUp.as_view(), name="signup"),
    path("login", HandeLogin.as_view(), name="login"),
    path("logout", HandelLogout.as_view(), name="handleLogout"),
    path("contact", Contact.as_view(), name="contact"),
    path("edit_profile", UserEditView.as_view(), name="edit_profile"),
    path("<int:pk>/profile", ShowProfilePageView.as_view(), name="show_profile"),
    path(
        "<int:pk>/edit_profile_page",
        EditProfilePageView.as_view(),
        name="edit_profile_page",
    ),
    path("create_profile", CreateProfilePage.as_view(), name="create_profile"),
    path("fav/<int:id>/", FavouriteAdd.as_view(), name="favourite_add"),
    path("profile/favourite", FavouriteList.as_view(), name="profile_favourite"),
    path("watch/<int:id>/", WatchLaterCourseAdd.as_view(), name="watch_later_add"),
    path(
        "profile/watch_later",
        WatchLaterCourseList.as_view(),
        name="profile_watch_later",
    ),
    path(
        "watch_playlist/<int:id>/",
        WatchLaterPlaylistItemAdd.as_view(),
        name="watch_later_playlist_add",
    ),
    path(
        "profile/watch_later_playlist",
        WatchLaterPlaylistItemList.as_view(),
        name="profile_watch_later_playlist",
    ),
]

playlist/playlist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

admin.site.site_header = "TechHub Admin"
admin.site.site_title = "TechHub Adminstration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("course_video.urls")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playlist/templates/course/List.html
{% extends 'course/base.html' %}
{% block body %}
    <button onclick="history.back()"><img src="https://cdn-icons-png.flaticon.com/512/3114/3114883.png " alt="" title="" class="img-small" width="30" height="30"></button>
    <center class="mx-2"><h1>{{title}}</h1></center>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">S.no</th>
          <th scope="col">List</th>
          <th scope="col">Action</th>
          <th scope="col">Time</th>
          <th scope="col">Current Status</th>
        </tr>
      </thead>
      <tbody>
        {% for dict in videoDetail %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td><a target="_blank" style="color: inherit;" href={{dict.link}}>{{ dict.list_item }}</a></td>
          <td>
          <a href={% url 'members:watch_later_playlist_add' dict.id %}>
            <img src="   https://cdn-icons-png.flaticon.com/512/833/833602.png " alt="" title="" class="img-small" width="20" height="20">
          </a>
        </td>
          <td>{{dict.time}}</td>



          <td>
            <div class="card">
              <div class="card-body">
                <form action="{% url 'course_video:getstatus' dict.id %}" method="post">
                  {% csrf_token %}
                  {% comment %} <label for="choice">Choice</label> {% endcomment %}
                  <select name="choice" class="form-control">
                    {% if dict.status == "Yet to Start" %}
                    <option value="Yet to Start" selected>Yet to Start</option>
                    {% else %}
                    <option value="Yet to Start">Yet to Start</option>
                    {% endif %}
                    {% if dict.status == "In Progress" %}
                    <option value="In Progress" selected>In Progress</option>
                    {% else %}
                    <option value="In Progress">In Progress</option>
                    {% endif %}
                    {% if dict.status == "On Hold" %}
                    <option value="On Hold" selected>On Hold</option>
                    {% else %}
                    <option value="On Hold">On Hold</option>
                    {% endif %}
                    {% if dict.status == "Completed" %}
                    <option value="Completed" selected>Completed</option>
                    {% else %}
                    <option value="Completed">Completed</option>
                    {% endif %}
                  </select>
                    <button type="submit" class="btn btn-dark my-2">Save</button>
                  </form>
                  </div>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
    </table>

{% endblock %}

playlist/templates/course/add_course.html
{% extends 'course/base.html' %}
{% block body %}
<form action="/add" , method="post">
  {% csrf_token %} {{form.as_p}}
  <button type="submit" class="btn btn-dark">ADD</button>
</form>
{% endblock body %}

playlist/templates/course/edit.html
{% extends 'course/base.html' %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        <center class="my-2"><h1>Edit Title </h1><center>
            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" name="title" id="title" value="{{course.title}}">
            </div>
            <button type="submit" class="btn btn-dark">Update</button>
        </form>
{% endblock body %}

playlist/templates/course/home.html
{% extends 'course/base.html' %} 
{% block title %} Home{% endblock title %}
{% block homeactive %} active {% endblock homeactive %}
{% block body %}

<div class="container">
  <div class="jumbotron my-3">
    <h1 class="display-4">Welcome to TechHub!</h1>
    <p class="lead">
      This Platform provide you all new and trending technologies to learn and
      explore.
    </p>
    <hr class="my-4" />
    <p>Technology is best when it brings people together.</p>
    <a class="btn btn-primary btn-lg" href="course" role="button"
      >Go to Course</a
    >
  </div>
</div>
<br></br>

{% endblock %}

playlist/templates/course/index.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}Course{% endblock title %}
{% block extra_head %}
  <link rel=”stylesheet” href=”{% static 'css/style.css' %}”>
{% endblock extra_head %}

{% load time_left %}

{% block nav %}
<div class="ml-auto form-inline">
{% comment %} <a href="download"  class="nav mr-2">Sample Excel</a> {% endcomment %}
<a href="course_video:upload" role="button" class="btn btn-success mr-2">Upload Excel</a>
  <a href="course_video:course_csv" role="button" class="btn btn-success mr-2">Download Excel</a>
</div>
{% endblock nav %}

{% block body %}

    <center class="my-2"><h1>List of Playlist</h1></center>
    <div class="ml-auto my-2">

      <a href="download" role="button" class="btn btn-success mr-2">Sample Excel</a>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">S.no</th>
            <th scope="col">Title</th>
            <th scope="col">Action</th>
            <th scope="col">Tag</th>
            <th scope="col">Progress</th>
            <th scope="col">Time Left</th>
          </tr>
        </thead>
        <tbody>

          {% for a in course %}
                    {% if a.public and user.is_authenticated %}
                    <tr>
                      <th scope="row">{{forloop.counter}}</th>
                      <td><a  style="color: inherit;" href="{% url 'course_video:listing' a.id %}">{{a.title}}</a></td>

                      {% if user.id == a.author.id %}
                        <td>
                          <a id="gotoicon" target="_blank" href={{a.link}}><img class="mx-2" src="https://cdn-icons-png.flaticon.com/512/709/709576.png" alt="Export free icon" title="Go to Link" width="20" height="20"></a>

                          <a href="{% url 'course_video:editing' a.id %}">
                          <img src="   https://cdn-icons-png.flaticon.com/512/1159/1159633.png " alt="" title="Edit title" class="img-small" width="20" height="20">
                          </a>
                          <a href={% url 'members:watch_later_add' a.id %}>
                            <img src="   https://cdn-icons-png.flaticon.com/512/833/833602.png " alt="" title="Watch Later" class="img-small" width="20" height="20">
                          </a>
                          <a href={% url 'members:favourite_add' a.id %}>
                            <img src="   https://cdn-icons-png.flaticon.com/512/8596/8596084.png " alt="" title="Add to favourite" class="img-small" width="20" height="20">
                          </a>
                        </td>

                        {% else %}
                        <td>
                          <a id="gotoicon" target="_blank" href={{a.link}}><img class="mx-2" src="https://cdn-icons-png.flaticon.com/512/709/709576.png" alt="Export free icon" title="Go to Link" width="20" height="20"></a>

                          <a href="{% url 'course_video:clone' a.id %}">
                            <img src="https://cdn-icons-png.flaticon.com/512/4662/4662661.png " alt="" title="Clone" class="img-small" width="20" height="20"></a>
                            <a href={% url 'members:watch_later_add' a.id %}>
                              <img src="   https://cdn-icons-png.flaticon.com/512/833/833602.png " alt="" title="Watch Later" class="img-small" width="20" height="20">
                            </a>
                            <a href={% url 'members:favourite_add' a.id %}>
                              <img src="   https://cdn-icons-png.flaticon.com/512/8596/8596084.png " alt="" title="Add to favourite" class="img-small" width="20" height="20">
                            </a>
                        </td>
                        {% endif %}
                        <td>
                        {% for tag in a.tags.all %}
                        <a href="{% url 'course_video:tag_listing' tag.slug %}">{{tag.name}}</a>
                      {% endfor %}
                    </td>
                    {% for item, values in per.items %}
                      {% if item == a.id %}
                        {% if user.id == a.author.id %}
                          <td>

                        <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-label="Example with label" style="width: {{values}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">{{values}}%</div>
                      </div>

                    </td>
                    {% else %}
                    <td>

                      <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-label="Example with label" style="width: 0%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">0%</div>
                      </div>
                    </td>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if user.is_authenticated and profile.time_preference == "H" %}

                      <td>{{ a.time_left | time_conversion:"H" }} hr left</td>
                    {% elif user.is_authenticated and profile.time_preference == "M" %}
                      <td>{{ a.time_left | time_conversion:"M" }} min left</td>
                    {% else %}
                      <td>{{ a.time_left | time_conversion:"S" }} sec left</td>
                    {% endif %}
                    </tr>
                    {% else %}

                    {% if user.id == a.author.id %}
                    <tr>
                    <th scope="row">{{forloop.counter}}</th>
                      <td><a  style="color: inherit;" href="{% url 'course_video:listing' a.id %}">{{a.title}}</a></td>
                        <td>

                          <a id="gotoicon" target="_blank" href={{a.link}}><img class="mx-2" src="https://cdn-icons-png.flaticon.com/512/709/709576.png" alt="Export free icon" title="Go to Link" width="20" height="20"></a>

                          <a href="{% url 'course_video:editing' a.id %}">
                            <img src="   https://cdn-icons-png.flaticon.com/512/1159/1159633.png " alt="" title="Edit title" class="img-small" width="20" height="20">
                            </a>
                            <a href={% url 'members:watch_later_add' a.id %}>
                              <img src="   https://cdn-icons-png.flaticon.com/512/833/833602.png " alt="" title="Watch Later" class="img-small" width="20" height="20">
                            </a>
                            <a href={% url 'members:favourite_add' a.id %}>
                              <img src="   https://cdn-icons-png.flaticon.com/512/8596/8596084.png " alt="" title="Add to favourite" class="img-small" width="20" height="20">
                            </a>
                        </td>
                      <td>
                      {% for tag in a.tags.all %}
                        <a href="{% url 'course_video:tag_listing' tag.slug %}">{{tag.name}}</a>
                          {% endfor %}
                        </td>
                    {% for item, values in per.items %}
                    {% if item == a.id %}
                    {% if user.id == a.author.id %}
                    <td>

                      <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-label="Example with label" style="width: {{values}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">{{values}}%</div>
                      </div>
                    </td>
                    {% else %}
                    <td>
                      <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-label="Example with label" style="width: 0%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">0%</div>
                      </div>
                    </td>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if user.is_authenticated and profile.time_preference == "H" %}

                      <td>{{ a.time_left | time_conversion:"H" }} hr left</td>
                    {% elif user.is_authenticated and profile.time_preference == "M" %}
                      <td>{{ a.time_left | time_conversion:"M" }} min left</td>
                    {% else %}
                      <td>{{ a.time_left | time_conversion:"S" }} sec left</td>
                    {% endif %}
                    {% else %}
                    <tr>

                    </tr>
                    {% endif %}

                  </tr>

                    {% endif %}
      {% endfor %}
    </tbody>
      </table>
      {% if is_paginated %}
<ul class="pagination">
{% if page_obj.has_previous %}
    <li>
        <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
    </li>
{% endif %}
    <li class="">
        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
    </li>
{% if page_obj.has_next %}
    <li>
        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
    </li>
{% endif %}
</ul>

{% endif %}
      {% endblock body %}

playlist/templates/course/search.html
{% extends 'course/base.html' %}

{% block title %} Search Results {% endblock title %}
{% block blogactive %} active {% endblock blogactive %}


{% block body %}
<div class="container my-2">
    <h2>Search results : </h2>
    {% for post in allCourse  %}
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-0">{{post.title}}</h3>
            <div class="my-2">
            	<a href="{{post.link}}" role="button" class="btn btn-primary">Checkout</a>
            </div>

        </div>
        <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
            </svg>
        </div>
        </div>

        {% endfor %}
    </div>
 {% endblock %}

playlist/templates/course/tag.html
{% extends 'course/base.html' %}

{% block title %} Similar Course {% endblock title %}
{% block blogactive %} active {% endblock blogactive %}


{% block body %}
<div class="container my-3">
    {% if tags %}
    {% for post in tags  %}
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-0">{{post.title}}</h3>
            <div class="my-2">
                <a href="{{post.link}}" role="button" class="btn btn-primary">Checkout</a>
            </div>

        </div>}
    </div>
    {% endfor %}
    {% else %}
    <p>No post related to that tag yet.</p>
    {% endif %}
</div>

 {% endblock %}

playlist/templates/course/upload.html
{% extends 'course/base.html' %}

{% block body %}
<form action="{% url "course_video:upload" %}" method="post" enctype="multipart/form-data" class="my-2">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   class= "btn btn-dark my-2">
        </form>

        <p></p>
    {% endblock body %}
</html>